cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
cask 'xquartz'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'
brew 'blackbox'
brew 'kubectl'
brew 'pinentry-mac'

cask '1password'
cask 'atom'
cask 'firefox'
cask 'google-chrome'
cask 'slack'
cask 'steam'
cask 'transmission'
cask 'vlc'
cask 'sublime-text'
cask 'visual-studio-code'
cask 'docker'
cask 'sourcetree'
cask 'spotify'
cask 'alfred'
cask 'telegram'
cask 'iterm2'
cask 'beyond-compare'
cask 'google-cloud-sdk'
